trigger: []
  #- feature/*
  #- hotfix/*
  #- bugfix/*
  #- release/*
  #- master
  #- main
  #- develop

parameters:

  - name: environment
    type: string
    displayName: 'Endereço do WebRIS para execução dos testes'
    default: 'https://webris.hml.app.ocph.rededor.com.br'

  - name: tag
    type: string
    displayName: 'Categoria a ser executada'
    default: 'CAT-02'

stages:

  - stage: Tests
    displayName: Run tests and quality analysis
    pool:
      name: RISPACS
    variables:
      BASE_URL: "${{ parameters.environment }}"
      NODE_OPTIONS: '--max_old_space_size=12288'
    jobs:

      - job: UnitTests
        displayName: Run tests
        timeoutInMinutes: 300
        steps:

          - task: NodeTool@0
            inputs:
              versionSpec: 18.x
            displayName: 'Install Node.js'

          - script: |
              sed -i 's/cucumber-json-formatter-mac/cucumber-json-formatter/g' package.json
            displayName: Configuring settings

          - script: npm install
            displayName: Install dependencies

          - ${{ if eq(parameters.tag, '') }}:
            - script: npm run cypress:headless-ci
              displayName: Run tests

          - ${{ if ne(parameters.tag, '') }}:
            - script: npm run cypress:headless-ci -- --env tags="@${{ parameters.tag }}"
              displayName: Run tests

          - task: PublishTestResults@2
            displayName: 'Publish the test reports'
            inputs:
              testResultsFiles: 'results/**/test-*.xml'
            condition: succeededOrFailed()
            continueOnError: true

          - task: PublishCucumberReport@1
            displayName: 'Publish cucumber report the test'
            inputs:
              jsonDir: 'cypress/report'
              outputPath: 'cypress/report'
            condition: succeededOrFailed()
            continueOnError: true
